package edu.university.pathwaycommons.PathwayCommons;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.zip.GZIPInputStream;

/**
 * This class extracts the downloaded compressed files need to populate moksiskaan database.
 */

public class extract {
	public void extractFile() {
		// location of downloaded compressed files
		File folder = new File(System.getProperty("user.home") + "/eclipse/SeleniumDownloads");
		File[] listOfFiles = folder.listFiles();

		for (File file : listOfFiles) {
			if (file.isFile()) {				
				try {
					FileInputStream fis = new FileInputStream(file.getAbsolutePath());					
					String targetfile = file.getParentFile() + "/" + file.getName().replace("gz", "txt");
					
					// removes the .DS_Store file generated by MacOs
					if (file.getName() == ".DS_Store") {
						continue;
					} else if (file.getName().endsWith(".txt")) {
						continue;
						// deletes the unnecessary files
					} else if (file.getName().contains("EXTENDED")) {
						file.delete();
					} else {
						// extract the files
						GZIPInputStream gzis = new GZIPInputStream(fis);
						
						byte[] buffer = new byte[1024];
						int length;
						
						FileOutputStream fos = new FileOutputStream(targetfile);
						
						while ((length = gzis.read(buffer)) > 0) {
							fos.write(buffer, 0, length);
						}
						
						fos.close();
						gzis.close();
						fis.close();
						System.out.println("Files extracted are " + file);
					}
				} catch (Exception e) {
					e.printStackTrace();
				}
			}			
		}
	}
}